### ISSUE TITLE
Per iniziare

### ISSUE THREAD

**Issue by aborruso** [emergenzeHack/terremotocentro_geodata#1]
Ciao @lorenzoperone e @alesarrett questo è il repo per i dati di cui abbiamo parlato.

Ho impostato come branch di default il gh-pages, perché è quello che useremo veramente e a cui corrisponderanno URL pubblici.

L'URL di base https://emergenzehack.github.io/terremotocentro_geodata/

**Comment by lorenzoperone** [comment]
Caricato shape, kml e geojson versione r05
