### ISSUE TITLE
Mappa amatricebeforeandafter non carica correttamente

### ISSUE THREAD

**Issue by lorenzoperone** [emergenzeHack/terremotocentro_geodata#2]
Quando si cambia zoom la mappa non visualizza l'immagine post sisma

**Comment by aborruso** [comment]
@lorenzoperone io (testando qui ondata.github.io/amatricebeforeandafter) non ho alcun problema

**Comment by lorenzoperone** [comment]
Il problema è nel repo migrato qui

**Comment by lorenzoperone** [comment]
Magari lo cancello...

**Comment by lorenzoperone** [comment]
Ora va :)

**Comment by aborruso** [comment]
Magia?

**Comment by lorenzoperone** [comment]
Ho corretto il file index.

Lorenzo Perone
twitter: @lorenzo_perone https://twitter.com/lorenzo_perone
photoblog: http://immagini.me

2016-08-29 10:55 GMT+02:00 Andrea Borruso notifications@github.com:
