### ISSUE TITLE
Automatizzare aggiornamento e download dei dati Copernicus

### ISSUE THREAD

**Issue by aborruso** [emergenzeHack/terremotocentro_geodata#4]
E' un'idea di @alesarrett 

>L'idea sarebbe quella di:
>- fare download degli zipfile (preferibilmente incrementale con un check giornaliero di cosa e se è cambiato)
>- szippare e selezionare per ora solo i settlements_poly_grading (edifici con valutazione dei danni)
>- fare un bel merge in un file unico
>- uploadare in github

Ale ha iniziato a mettere in file le cose [qui]: https://github.com/emergenzeHack/terremotocentro_geodata/blob/gh-pages/CopernicusEMS/EMSR190/EMSR190_scraping.ipynb

Scaricati tutti i link utili (cosa già fatta), la prima barriera è superare il click per l'accettazione del download:

![image](https://cloud.githubusercontent.com/assets/30607/19998612/1848afec-a26e-11e6-8b82-dd1aaed362f7.png)

**Comment by aborruso** [comment]
@alesarrett sembra che basti soltanto accettare un cookie. Testato con curl, che si può mettere nel loop.

Questo un codice di esempio:

``` bash
curl -s -c cookie  "http://emergency.copernicus.eu/mapping/download/137779/EMSR190_32ACQUASANTATERME_GRADING_OVERVIEW_v1_vector.zip"


curl -b cookie -s "http://emergency.copernicus.eu/mapping/download/137779/EMSR190_32ACQUASANTATERME_GRADING_OVERVIEW_v1_vector.zip" -H "Origin: http://emergency.copernicus.eu" -H "Accept-Encoding: gzip, deflate" -H "Accept-Language: it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4" -H "Upgrade-Insecure-Requests: 1" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36" -H "Content-Type: application/x-www-form-urlencoded" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Cache-Control: max-age=0" -H "Referer: http://emergency.copernicus.eu/mapping/download/137779/EMSR190_32ACQUASANTATERME_GRADING_OVERVIEW_v1_vector.zip" -H "Connection: keep-alive" --data "confirmation=1^&op=+Download+file+^&form_build_id=form-wfWtSFuhPbanIpxEiVM8LPHnvLF5LEOuakUYLcXkCeI^&form_id=emsmapping_disclaimer_download_form" --compressed > EMSR190_32ACQUASANTATERME_GRADING_OVERVIEW_v1_vector.zip
```

**Comment by aborruso** [comment]
@alesarrett ho visto il tuo notebook aggiornato con il richiamo via cURL dei file zip da scaricare. Quando passi al richiamo del comando in bash

```
! curl -s -c cookie zipurltot
```

al nome della variabile devi anteporre `$` perché non siamo più in python. 

Questo a un primo rapido check

**Comment by alesarrett** [comment]
Grazie Andrea, ho modificato, semplificato l'ultimo blocco di comendi e testato e ora il download di tutti gli zip files funziona!

**Comment by aborruso** [comment]
@alesarrett non ti resta che chiudere la issue :)

**Comment by alesarrett** [comment]
La questione è più ampia (download, aggiornamento e upload) ma concordo sulla chiusura di questo issue e con l'apertura eventuale di issue più definiti che siano focalizzati su problemi specifici.
