### ISSUE TITLE
Licenza e riuso

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro_geodata#8]
Ciao @geofrizz ho elaborato una versione un po' più generalizzata di questo script per gestire più ZIP di più emergenze in modo automatico. Volevo farne un repo Github aperto, ma purtroppo non vedo licenza di riuso su questo file...sai dirmi come darti i crediti di autore allo script di partenza?
Grazie!

**Comment by geofrizz** [comment]
Ciao @iltempe,
no, non ne ho la piu' pallida idea.
Avrei dovuto scrivere io qualcosa nel file iniziale, come commento ??
Esiste uno standard da utilizzare ??
Non so cosa rispondere alla tua domanda.
Grazie a te.

**Comment by iltempe** [comment]
@geofrizz in realtà è una scelta tua da definire sulla base di quanto vuoi che il tuo script venga riusato. attualmente io ovviamente vorrei citare questo file come "fonte" del mio perchè effettivamente ho riusato il tuo (se me lo concedi). In ogni caso per scegliere una licenza da dare ad un sw qui alcune indicazioni utili https://choosealicense.com/

**Comment by iltempe** [comment]
@geofrizz ho fatto questo repo dove vorrei continuare questo sviluppo ed archiviare un po' di script utili per gestire EMS. attualmente c'è il mio fatto a partire dal tuo ed i crediti a te. Volevo solo sincerarmi di poterlo fare (dato appunto che non hai esplicitato la licenza). tutto qua. Fammi sapere se la cosa per te è ok. https://github.com/emergenzeHack/ems_toolkit

**Comment by geofrizz** [comment]
@iltempe,
si, si, si,  sentiti libero di usarlo senza limiti ne vincoli.
Ciao
